### ISSUE TITLE
underscore is too big

### ISSUE THREAD

**Issue by bojoyzhou** [opudalo/ajax#2]
I think it's better if the underscore can be removed

**Comment by opudalo** [comment]
Where do you see it?

**Comment by bojoyzhou** [comment]
seach on `github.com`

**Comment by opudalo** [comment]
can you be more specific? Link or anything.

**Comment by bojoyzhou** [comment]
i need an `ajax` module, so I search `es6 ajax` on github. 
https://github.com/search?utf8=✓&q=es6+ajax

**Comment by opudalo** [comment]
back to your first question. 
where do you see underscore? 
I do not see it.

**Comment by bojoyzhou** [comment]
Sorry!
I've made a mistake. That module which contain undersore is installed by `npm install ajax`.
Very sorry to have wasted your time.

**Comment by opudalo** [comment]
No worries :)
